apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniffer-api
  namespace: sniffer
  labels:
    app: sniffer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sniffer-api
  template:
    metadata:
      labels:
        app: sniffer-api
    spec:
      containers:
        - name: api
          image: artu0s/sniffer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ELASTICSEARCH_URL
              value: "http://elasticsearch:9200"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
