apiVersion: v1
kind: Secret
metadata:
  name: sniffer-secrets
  namespace: sniffer
type: Opaque
stringData:
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  KAGGLE_KEY: "your-api-key"
  KAGGLE_DATASET_URL: "https://www.kaggle.com/api/v1/datasets/download/olgagmiufana1/fragrantica-com-fragrance-dataset"
